# Generated by Django 3.1.4 on 2021-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
